version: '3.1'

services:
    redmine:
        image: nordit/redmine:1
# указать расположение базы данных
        volumes:
          - D:\backup\sharedock\redmine\app_volume:/usr/src/redmine/
          - D:\backup\sharedock:/sharedock/
          - D:\backup\sharedock\redmine\files:/usr/src/redmine/files/
        restart: always
        environment:
          REDMINE_DB_MYSQL: redmine
          REDMINE_DB_USERNAME: redmine
          REDMINE_DB_PASSWORD: redmine
        ports:
          - 80:3000
    mysql:
      image: mysql:5.7.30
      volumes:
        - D:\mysql/var/lib/mysql/
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD_FILE:
        MYSQL_DATABASE: redmine
        MYSQL_USER: redmine
        MYSQL_PASSWORD: redmine


# для запуска контейнера
# docker-compose -f redmine.yml up
