version: '3.1'

services:
    redmine:
        image: nordretail/redmine:latest
        volumes:
          - /sharedock/redmine/app_volume:/usr/src/redmine/
          - /sharedock:/sharedock/
          - /sharedock/redmine/files:/usr/src/redmine/files/
        restart: always
        environment:
          REDMINE_DB_MYSQL: redmine
          REDMINE_DB_USERNAME: redmine
          REDMINE_DB_PASSWORD: redmine
        ports:
          - 80:3000
# path to DB
    mysql:
      image: mysql:5.7.30
      volumes:
        - D:\mysql:/var/lib/mysql/
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: Lbvtnhf7373
        MYSQL_DATABASE: redmine
        MYSQL_USER: redmine
        MYSQL_PASSWORD: redmine


# For run Instance:
# docker-compose -f redmine.yml up
