version: '3.1'


services:
    mysql:
        image: mysql:5.7.30
        volumes:
          - D:\mysql/var/lib/mysql/
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: Lbvtnhf7373
          REDMINE_DB_MYSQL: redmine
          REDMINE_DB_USERNAME: redmine
          REDMINE_DB_PASSWORD: redmine


#>docker run --name mysql-cont -v D:\mysql:/var/lib/mysql -e  -e MYSQL_DATABASE=redmine -e MYSQL_USER=redmine -e MYSQL_PASSWORD=redmine -d  mysql:5.7
  #.30

