verison: '3.1'

services:
    redmine:
        image: nordit/redmine:1
        volumes:
          - D:\backup\sharedock\redmine\app_volume:/usr/src/redmine/
          - D:\backup\sharedock:/sharedock/
          - D:\backup\sharedock\redmine\files:/usr/src/redmine/files/
        restart: always
        environment:
          REDMINE_DB_MYSQL: redmine
          REDMINE_DB_USERNAME: redmine
          REDMINE_DB_PASSWORD: redmine
        ports:
          - 80:3000