version: '3.8'

volumes:
  postgres_db:
    external: true
    name: postgres_db


services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Lbvtnhf7373

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


# docker run -d --name some-postgres --network some-network -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=redmine postgres